### ISSUE TITLE
Opening this web component in the store's separate window preview, does not show anything

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-creative-industries#11]
It is unclear if this is a bug of this web component or the store, needs investigation...

**Comment by lelebus** [comment]
I found the issue and I am going to fix it.
Just be careful to add a height and width to the webcomp also in the external window. Otherwise, it won't show the component anyway.

**Comment by Piiit** [comment]
@lelebus That is currently not possible, could you please add a default height and width if it is not given from outside?

**Comment by Piiit** [comment]
@lelebus Still not working

**Comment by Piiit** [comment]
It also downloads tiles from cartodb which are outside south tyrol:

![Selection_124](https://user-images.githubusercontent.com/6096063/81835949-1ec81d00-9543-11ea-8b2f-0647fc82db21.png)

**Comment by Piiit** [comment]
@lelebus Same problem in v0.8.1

**Comment by lelebus** [comment]
You didn't specify the new props added in #18

**Comment by Piiit** [comment]
@lelebus I tried that, but it does not show anyway...

See
https://api.webcomponents.opendatahub.bz.it/preview/f1321372-6629-4912-a331-77d5d91dd646/v0.8.1?attribs=locale=%22it%22;height=%221300%22;width=%221800%22;

which result in the following code:

```html
<!DOCTYPE HTML>
<html>
<head>
    <title>Open Data Hub - Web Component Store - Simple Previewer</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <style>
        .responsive {
            position: relative;
        }
    </style>
</head>
<body>
    <div class="responsive"><webcomp-creative-industries locale="it" height="1300" width="1800"></webcomp-creative-industries></div>
    
    <script src="https://cdn.webcomponents.opendatahub.bz.it/dist/f1321372-6629-4912-a331-77d5d91dd646/v0.8.1/webcomp-creative-industries.min.js"></script>
    
</body>
</html>
```

**Comment by lelebus** [comment]
What you are passing as props are String values. This means you should add a unit, for example, px.

Sorry, I should have specified.

**Comment by Piiit** [comment]
@lelebus Thanks for the information, it works like this. Could you please add this information to the README under "Attributes", and explain in detail what is possible and what not. As far as I understood it is a CSS attribute, right?

**Comment by lelebus** [comment]
Yes, it is an inline css attribute for the top element.
I will specify it in the README

**Comment by Piiit** [comment]
@lelebus @ohnewein Thanks it works now in version 0.8.2
