### ISSUE TITLE
Flashbeing is the default icon for all experts?

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/webcomp-creative-industries#12]
![Screenshot from 2020-05-12 15-50-58](https://user-images.githubusercontent.com/414797/81700185-9ffeb180-9468-11ea-81d0-b143648a91df.png)

**Comment by Piiit** [comment]
@ohnewein From the last conversation:

> Rimane aperto il discorso logo delle varie aziende. Per ora e' stato impostato il logo di FlashBeing come placeholder.

This is the last missing feature

**Comment by Piiit** [comment]
@lelebus 
I thought about this again, and think we should have a neutral placeholder until the proper solution is found. With that the component would be already usable directly... without a "wrong" company logo assigned... Could you please change that in the meantime?

**Comment by Piiit** [comment]
@lelebus @ohnewein Solved in v0.8.0
