### ISSUE TITLE
Hide empty categories from list

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/webcomp-creative-industries#13]
If a category is empty, like "Software & Games" it should not appear at all in the list. Otherwise users navigate into empty dead ends...

![Screenshot from 2020-05-12 15-53-24](https://user-images.githubusercontent.com/414797/81700310-c7ee1500-9468-11ea-8f95-6f160ba505e0.png)

**Comment by lelebus** [comment]
This happens for sectors automatically.
It was decided with IDM that this is not a necessary feature for Industries, since there are at least one point for each category for sure.

**Comment by ohnewein** [comment]
This means data is not complete yet. Because I found the category/sector without entries.

But if it is fine for IDM and it would be too much effort. I am fine with it.

**Comment by lelebus** [comment]
Yes, data is not complete yet. There are just 11 sample entries for testing purposes
