### ISSUE TITLE
Use the API

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-creative-industries#4]
Please use the API v2 calls to get data, I do not know how long it would take to get all data from our survey, but for now it would be useful for testing to get the data that is there already from the real server's API...

```http
GET https://mobility.api.opendatahub.bz.it/v2/api/flat/CreativeIndustry?limit=200
```

@lelebus FYI

**Comment by lelebus** [comment]
Is there a documentation that describes the fields?

**Comment by Piiit** [comment]
@lelebus Hi, and sorry for the late reply... 
Let me explain the API a bit with the following example:
```
 {
      "sactive": false,
      "savailable": true,
      "scode": "1I5Zj7JHprwLhzl9ktXJO-7v7x3rh1ysGbiblZgZYCXU:AriannaMoroderMontellostrasse22,39100Bozen",
      "scoordinate": {
        "x": 11.343842,
        "y": 46.504509,
        "srid": 4326
      },
      "smetadata": {
        "name": "Arianna Moroder",
        "sector": "Produktdesign und Mode",
        "address": "Montellostrasse 22, 39100 Bozen",
        "website": "http://www.ariannamoroder.com/",
        "contacts": "ariannamoroder@gmail.com",
        "description": {
          "de": "KOMMT NOCH"
        }
      },
      "sname": "Arianna Moroder",
      "sorigin": "1I5Zj7JHprwLhzl9ktXJO-7v7x3rh1ysGbiblZgZYCXU",
      "stype": "CreativeIndustry"
    }
```

All fields except of the attributes of `smetadata` are fixed and will not change. It could be that some are NULL thou, for instance a `scoordinate`, but all other fields have a non-null constraint.

The `smetadata` content is the parsed content of the spreadsheet (see email), which gets not checked from the importer or API. So there it is whatever gets put. The API cannot guarantee any structure, except from the agreements with the spreadsheet authors.

The documentation is currently under development and will follow soon.

**Comment by lelebus** [comment]
As described in the emails, there are some incompatibilities with the structure of the component, that was agreed on the beginning of the project.
It is nothing impossible to solve. But the industry of each entity should be defined by a key (I used values from 0 to 11). The reason is to be consistent for different languages and be sure to use the right predefined icons.

I was awaiting a response from Luca. How can we move forward?

**Comment by Piiit** [comment]
@lelebus Done... Thank you.

Please test it on https://webcomponents.opendatahub.bz.it/webcomponent/f1321372-6629-4912-a331-77d5d91dd646 and provide some feedback.

We will do the same and open some issues here, if we find bugs.

Nice work, thank you
