### ISSUE TITLE
As a user of the creative industries web component, I want to have it integrated into the store to see it in action and to give feedback

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-creative-industries#6]
Related to the PR https://github.com/noi-techpark/webcomp-creative-industries/pull/5

- [x] PR has conflicts, wait for Flashbeing to solve them
> Solved by me
- [x] @lelebus Check README and functionalities
> Nothing about the need to integrate also images and script...vue to work correctly
- [x] Create a docker build and development environment with docker-compose
- [x] Prepare a wcs-manifest.json and screenshot
- [x] Integrate it into the development store
- [x] Inform contributors and copyright holders that the feedback session is open
> I will do this during the dedicated meeting
- [x] @lelebus Still not using the API https://github.com/noi-techpark/webcomp-creative-industries/issues/4
> This issue is not solved, but we ignore it for now, since we have a  dedicated meeting to discuss further steps, and ordering of actions from all contributors.
- [x] @lelebus Not minified and packed correctly: https://github.com/noi-techpark/webcomp-creative-industries/issues/2

So this user story is done, altough with a prototype component that uses mock API calls only. However, for a first feedback session, this works-for-me :-)

**Comment by Piiit** [comment]
@lelebus Could you please fix the issues mentioned above... Thank you

**Comment by lelebus** [comment]
> Related to the PR #5
> 
>     * [x]  PR has conflicts, wait for Flashbeing to solve them
> 
> 
> > Solved by me
> 
>     * [ ]  @lelebus Check README and functionalities
> 
> 
> > Nothing about the need to integrate also images and script...vue to work correctly
> 
>     * [x]  Create a docker build and development environment with docker-compose
> 
>     * [x]  Prepare a wcs-manifest.json and screenshot
> 
>     * [x]  Integrate it into the development store
> 
>     * [ ]  Inform contributors and copyright holders that the feedback session is open
> 
>     * [ ]  @lelebus Still not using the API #4
> 
>     * [x]  @lelebus Not minified and packed correctly: #2

**Comment by Piiit** [comment]
> @lelebus Check README and functionalities
>    Nothing about the need to integrate also images and script...vue to work correctly
>>    What do you need me to check?

It was the part about the integration of the vue package and images, which were missing.

**Comment by Piiit** [comment]
@LucaMiotto 
I wrote an email about this web component prototype and that it is possible to test it. In addition, we have a meeting today afternoon (2020-04-16)
